### ISSUE TITLE
Add a global ReSpec API

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#3089]
```
document.respec = {
  // same as window.respecVersion
  version: string,
  errors: ReSpecError[],
  warnings: ReSpecError[],
  // same as document.respecIsReady
  ready: Promise<void>,
  // catch ReSpec errors/warnings (extends EventTarget)
  addEventListener: ("error" | "warning") => void,
  // export static HTML
  toHTML: () => Promise<string>,
}
```
- [x] `document.respec` basic (https://github.com/w3c/respec/pull/3082)
- [x] `document.respec.ready` (https://github.com/w3c/respec/pull/3082)
- [x] deprecate `document.respecIsReady` (https://github.com/w3c/respec/pull/3090)
- [x] `document.respec.toHTML()` - Part of https://github.com/w3c/respec/issues/2889 (https://github.com/w3c/respec/pull/3403)
- [x] `document.respec.errors[]`, `document.respec.warnings[]` - Closes https://github.com/w3c/respec/issues/1084 (https://github.com/w3c/respec/pull/3348)
- [ ] `document.respec.addEventListener("error" | "warning")` - Part of https://github.com/w3c/respec/issues/3035 (https://github.com/w3c/respec/pull/3338)

**Comment by dontcallmedom** [comment]
I'm not sure if it makes sense in this context, but one feature [I needed recently]( which could be hosted in this global API: in a postProcess script in ReSpec, I [wanted to use data from the WebIDL parser](https://github.com/w3c/webrtc-stats/pull/580/files#diff-98a5b017f8b861a70f52aee2a9a2bb55R19), but there is no way to access the parser or the parsed IDL tree right

**Comment by sidvishnoi** [comment]
I'm not sure if `document.respec` would be the right place to expose this as I would like to keep the API surface as small as possible here to avoid any breaking changes.
FWIW, we do have plans for a new plugins API (See https://github.com/w3c/respec/issues/1976#issuecomment-659673129), where it might be easier to expose this functionality.
